version: "3"
services:
  setubot1:
    image: howrain/hoshinobot
    restart: always
    container_name: hoshinobot
    volumes:
      - /home/HoshinoBot/hoshino:/HoshinoBot/hoshino
      - /home/HoshinoBot/run.py:/HoshinoBot/run.py
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    command: python python run.py
