version: "3"
services:
  setubot1:
    image: howrain/hoshinobot
    restart: always
    container_name: hoshinobot
    volumes:
      - /home/HoshinoBot/hoshino:/home/HoshinoBot/hoshino
      - /home/HoshinoBot/res:/home/HoshinoBot/res
      - /home/HoshinoBot/data:/home/HoshinoBot/data
      - /home/HoshinoBot/run.py:/home/HoshinoBot/run.py
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    command:
      - pip install -r requirements.txt
      - python run.py
